all: constructor controller readInput install start rule getFunction wired legalAddr alreadyInstall cumulate pathInit

constructor:
	g++ -c constructor.cpp

controller:
	g++ -c controller.cpp

readInput:
	g++ -c readInput.cpp

install:
	g++ -c install.cpp

start:
	g++ -c start.cpp

rule:
	g++ -c rule.cpp

getFunction:
	g++ -c getFunction.cpp

wired:
	g++ -c wired.cpp

legalAddr:
	g++ -c legalAddr.cpp

alreadyInstall:
	g++ -c alreadyInstall.cpp

cumulate:
	g++ -c cumulate.cpp

pathInit:
	g++ -c pathInit.cpp
