all: constructor controller readInput install start rule getFunction wired legalAddr cumulate pathInit modifyCap vecdot vecdis wirelessSP wireless updateTCAM modCap recrdPrev

constructor:
	g++ -c constructor.cpp

controller:
	g++ -c controller.cpp

readInput:
	g++ -c readInput.cpp

install:
	g++ -c install.cpp

start:
	g++ -c start.cpp

rule:
	g++ -c rule.cpp

getFunction:
	g++ -c getFunction.cpp

wired:
	g++ -c wired.cpp

legalAddr:
	g++ -c legalAddr.cpp

cumulate:
	g++ -c cumulate.cpp

pathInit:
	g++ -c pathInit.cpp

modifyCap:
	g++ -c modifyCap.cpp

vecdot:
	g++ -c vecdot.cpp

vecdis:
	g++ -c vecdis.cpp

wirelessSP:
	g++ -c wirelessSP.cpp

wireless:
	g++ -c wireless.cpp

updateTCAM:
	g++ -c updateTCAM.cpp

modCap:
	g++ -c modCap.cpp

recrdPrev:
	g++ -c recrdPrev.cpp
