all: constructor controller readInput install start rule getFunction wired legalAddr cumulate pathInit vecdot vecdis updateTCAM modCap recrdPrev blockFlow resumeFlow begTransmission endTransmission

constructor:
	g++ -c constructor.cpp

controller:
	g++ -c controller.cpp

readInput:
	g++ -c readInput.cpp

install:
	g++ -c install.cpp

start:
	g++ -c start.cpp

rule:
	g++ -c rule.cpp

getFunction:
	g++ -c getFunction.cpp

wired:
	g++ -c wired.cpp

legalAddr:
	g++ -c legalAddr.cpp

cumulate:
	g++ -c cumulate.cpp

pathInit:
	g++ -c pathInit.cpp

vecdot:
	g++ -c vecdot.cpp

vecdis:
	g++ -c vecdis.cpp

updateTCAM:
	g++ -c updateTCAM.cpp

modCap:
	g++ -c modCap.cpp

recrdPrev:
	g++ -c recrdPrev.cpp

blockFlow:
	g++ -c blockFlow.cpp

resumeFlow:
	g++ -c resumeFlow.cpp

begTransmission:
	g++ -c begTransmission.cpp

endTransmission:
	g++ -c endTransmission.cpp
